version: "3.3"
services:
  bootstrapper:
    image: kollaps:2.0
    command: ["-s", "14f75304-d357-4e88-bb1c-d6eb63a3c2bc"]
    deploy:
      mode: global
    environment:
      KOLLAPS_UUID: '14f75304-d357-4e88-bb1c-d6eb63a3c2bc'
      KOLLAPS_ORCHESTRATOR: swarm
      NUMBER_OF_GODS: 1
      POOL_PERIOD: 0.05
      MAX_FLOW_AGE: 2
    labels:
      boot14f75304-d357-4e88-bb1c-d6eb63a3c2bc: "true"
    volumes:
      - '/lib/modules:/lib/modules/'
      - '/usr/src:/usr/src/'
      - '/sys/:/sys/'
      - '/home/tiagoduarte25/Desktop/thesis/quicsand-c/multiple_clients.xml:/topology.xml'
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    networks:
      - KollapsNet

  dashboard-14f75304-d357-4e88-bb1c-d6eb63a3c2bc:
    image: kollaps/dashboard:1.0
    ports:
      - "8088:8088"
    hostname: dashboard
    deploy:
      replicas: 1
    environment:
      KOLLAPS_UUID: '14f75304-d357-4e88-bb1c-d6eb63a3c2bc'
      KOLLAPS_ORCHESTRATOR: swarm
    networks:
      - KollapsNet
      - outside

  client1-14f75304-d357-4e88-bb1c-d6eb63a3c2bc:
    image: quicsand_client
    entrypoint: ["/bin/sh", "-c", "mkfifo /tmp/Kollaps_hang; exec /bin/sh <> /tmp/Kollaps_hang #"]
    command: ['server','1']
    hostname: client1
    labels:
      14f75304-d357-4e88-bb1c-d6eb63a3c2bc: "true"
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
    environment:
      KOLLAPS_UUID: '14f75304-d357-4e88-bb1c-d6eb63a3c2bc'
      KOLLAPS_ORCHESTRATOR: swarm
    networks:
      - KollapsNet

  client2-14f75304-d357-4e88-bb1c-d6eb63a3c2bc:
    image: quicsand_client
    entrypoint: ["/bin/sh", "-c", "mkfifo /tmp/Kollaps_hang; exec /bin/sh <> /tmp/Kollaps_hang #"]
    command: ['server','1']
    hostname: client2
    labels:
      14f75304-d357-4e88-bb1c-d6eb63a3c2bc: "true"
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
    environment:
      KOLLAPS_UUID: '14f75304-d357-4e88-bb1c-d6eb63a3c2bc'
      KOLLAPS_ORCHESTRATOR: swarm
    networks:
      - KollapsNet

  client3-14f75304-d357-4e88-bb1c-d6eb63a3c2bc:
    image: quicsand_client
    entrypoint: ["/bin/sh", "-c", "mkfifo /tmp/Kollaps_hang; exec /bin/sh <> /tmp/Kollaps_hang #"]
    command: ['server','1']
    hostname: client3
    labels:
      14f75304-d357-4e88-bb1c-d6eb63a3c2bc: "true"
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
    environment:
      KOLLAPS_UUID: '14f75304-d357-4e88-bb1c-d6eb63a3c2bc'
      KOLLAPS_ORCHESTRATOR: swarm
    networks:
      - KollapsNet

  server-14f75304-d357-4e88-bb1c-d6eb63a3c2bc:
    image: quicsand_server
    entrypoint: ["/bin/sh", "-c", "mkfifo /tmp/Kollaps_hang; exec /bin/sh <> /tmp/Kollaps_hang #"]
    hostname: server
    labels:
      14f75304-d357-4e88-bb1c-d6eb63a3c2bc: "true"
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
    environment:
      KOLLAPS_UUID: '14f75304-d357-4e88-bb1c-d6eb63a3c2bc'
      KOLLAPS_ORCHESTRATOR: swarm
    networks:
      - KollapsNet

networks:
  KollapsNet:
    external:
      name: kollaps_network
  outside:
    driver: overlay

