version: "3.3"
services:
  bootstrapper:
    image: kollaps:2.0
    command: ["-s", "26c43604-b0d5-473a-825c-c22122ee4df1"]
    deploy:
      mode: global
    environment:
      KOLLAPS_UUID: '26c43604-b0d5-473a-825c-c22122ee4df1'
      KOLLAPS_ORCHESTRATOR: swarm
      NUMBER_OF_GODS: 1
      POOL_PERIOD: 0.05
      MAX_FLOW_AGE: 2
    labels:
      boot26c43604-b0d5-473a-825c-c22122ee4df1: "true"
    volumes:
      - '/lib/modules:/lib/modules/'
      - '/usr/src:/usr/src/'
      - '/sys/:/sys/'
      - '/home/tiagoduarte25/Desktop/thesis/quicsand-c/topology.xml:/topology.xml'
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    networks:
      - KollapsNet

  dashboard-26c43604-b0d5-473a-825c-c22122ee4df1:
    image: kollaps/dashboard:1.0
    ports:
      - "8088:8088"
    hostname: dashboard
    deploy:
      replicas: 1
    environment:
      KOLLAPS_UUID: '26c43604-b0d5-473a-825c-c22122ee4df1'
      KOLLAPS_ORCHESTRATOR: swarm
    networks:
      - KollapsNet
      - outside

  client1-26c43604-b0d5-473a-825c-c22122ee4df1:
    image: quicsand_client
    entrypoint: ["/bin/sh", "-c", "mkfifo /tmp/Kollaps_hang; exec /bin/sh <> /tmp/Kollaps_hang #"]
    command: ['server','1']
    hostname: client1
    labels:
      26c43604-b0d5-473a-825c-c22122ee4df1: "true"
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
    environment:
      KOLLAPS_UUID: '26c43604-b0d5-473a-825c-c22122ee4df1'
      KOLLAPS_ORCHESTRATOR: swarm
    networks:
      - KollapsNet

  client2-26c43604-b0d5-473a-825c-c22122ee4df1:
    image: quicsand_client
    entrypoint: ["/bin/sh", "-c", "mkfifo /tmp/Kollaps_hang; exec /bin/sh <> /tmp/Kollaps_hang #"]
    command: ['server','1']
    hostname: client2
    labels:
      26c43604-b0d5-473a-825c-c22122ee4df1: "true"
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
    environment:
      KOLLAPS_UUID: '26c43604-b0d5-473a-825c-c22122ee4df1'
      KOLLAPS_ORCHESTRATOR: swarm
    networks:
      - KollapsNet

  client3-26c43604-b0d5-473a-825c-c22122ee4df1:
    image: quicsand_client
    entrypoint: ["/bin/sh", "-c", "mkfifo /tmp/Kollaps_hang; exec /bin/sh <> /tmp/Kollaps_hang #"]
    command: ['server','1']
    hostname: client3
    labels:
      26c43604-b0d5-473a-825c-c22122ee4df1: "true"
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
    environment:
      KOLLAPS_UUID: '26c43604-b0d5-473a-825c-c22122ee4df1'
      KOLLAPS_ORCHESTRATOR: swarm
    networks:
      - KollapsNet

  server-26c43604-b0d5-473a-825c-c22122ee4df1:
    image: quicsand_server
    entrypoint: ["/bin/sh", "-c", "mkfifo /tmp/Kollaps_hang; exec /bin/sh <> /tmp/Kollaps_hang #"]
    hostname: server
    labels:
      26c43604-b0d5-473a-825c-c22122ee4df1: "true"
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
    environment:
      KOLLAPS_UUID: '26c43604-b0d5-473a-825c-c22122ee4df1'
      KOLLAPS_ORCHESTRATOR: swarm
    networks:
      - KollapsNet

networks:
  KollapsNet:
    external:
      name: kollaps_network
  outside:
    driver: overlay

