version: "3.3"
services:
  bootstrapper:
    image: kollaps:2.0
    command: ["-s", "d0958dfc-5125-4166-a2e6-416d0c971a3e"]
    deploy:
      mode: global
    environment:
      KOLLAPS_UUID: 'd0958dfc-5125-4166-a2e6-416d0c971a3e'
      KOLLAPS_ORCHESTRATOR: swarm
      NUMBER_OF_GODS: 1
      POOL_PERIOD: 0.05
      MAX_FLOW_AGE: 2
    labels:
      bootd0958dfc-5125-4166-a2e6-416d0c971a3e: "true"
    volumes:
      - '/lib/modules:/lib/modules/'
      - '/usr/src:/usr/src/'
      - '/sys/:/sys/'
      - '/home/tiagoduarte25/Desktop/thesis/quicsand-c/resources/topologies/high_latency.xml:/topology.xml'
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    networks:
      - KollapsNet

  dashboard-d0958dfc-5125-4166-a2e6-416d0c971a3e:
    image: kollaps/dashboard:1.0
    ports:
      - "8088:8088"
    hostname: dashboard
    deploy:
      replicas: 1
    environment:
      KOLLAPS_UUID: 'd0958dfc-5125-4166-a2e6-416d0c971a3e'
      KOLLAPS_ORCHESTRATOR: swarm
    networks:
      - KollapsNet
      - outside

  client1-d0958dfc-5125-4166-a2e6-416d0c971a3e:
    image: quicsand
    entrypoint: ["/bin/sh", "-c", "mkfifo /tmp/Kollaps_hang; exec /bin/sh <> /tmp/Kollaps_hang #"]
    command: ['server','1']
    hostname: client1
    labels:
      d0958dfc-5125-4166-a2e6-416d0c971a3e: "true"
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
    environment:
      KOLLAPS_UUID: 'd0958dfc-5125-4166-a2e6-416d0c971a3e'
      KOLLAPS_ORCHESTRATOR: swarm
    networks:
      - KollapsNet

  client2-d0958dfc-5125-4166-a2e6-416d0c971a3e:
    image: quicsand
    entrypoint: ["/bin/sh", "-c", "mkfifo /tmp/Kollaps_hang; exec /bin/sh <> /tmp/Kollaps_hang #"]
    command: ['server','1']
    hostname: client2
    labels:
      d0958dfc-5125-4166-a2e6-416d0c971a3e: "true"
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
    environment:
      KOLLAPS_UUID: 'd0958dfc-5125-4166-a2e6-416d0c971a3e'
      KOLLAPS_ORCHESTRATOR: swarm
    networks:
      - KollapsNet

  client3-d0958dfc-5125-4166-a2e6-416d0c971a3e:
    image: quicsand
    entrypoint: ["/bin/sh", "-c", "mkfifo /tmp/Kollaps_hang; exec /bin/sh <> /tmp/Kollaps_hang #"]
    command: ['server','1']
    hostname: client3
    labels:
      d0958dfc-5125-4166-a2e6-416d0c971a3e: "true"
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
    environment:
      KOLLAPS_UUID: 'd0958dfc-5125-4166-a2e6-416d0c971a3e'
      KOLLAPS_ORCHESTRATOR: swarm
    networks:
      - KollapsNet

  server-d0958dfc-5125-4166-a2e6-416d0c971a3e:
    image: quicsand
    entrypoint: ["/bin/sh", "-c", "mkfifo /tmp/Kollaps_hang; exec /bin/sh <> /tmp/Kollaps_hang #"]
    hostname: server
    labels:
      d0958dfc-5125-4166-a2e6-416d0c971a3e: "true"
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
    environment:
      KOLLAPS_UUID: 'd0958dfc-5125-4166-a2e6-416d0c971a3e'
      KOLLAPS_ORCHESTRATOR: swarm
    networks:
      - KollapsNet

networks:
  KollapsNet:
    external:
      name: quicsand_network
  outside:
    driver: overlay

