version: "3.3"
services:
  bootstrapper:
    image: kollaps:2.0
    command: ["-s", "f77c0191-ea42-4ed3-87a3-853354728fea"]
    deploy:
      mode: global
    environment:
      KOLLAPS_UUID: 'f77c0191-ea42-4ed3-87a3-853354728fea'
      KOLLAPS_ORCHESTRATOR: swarm
      NUMBER_OF_GODS: 1
      POOL_PERIOD: 0.05
      MAX_FLOW_AGE: 2
    labels:
      bootf77c0191-ea42-4ed3-87a3-853354728fea: "true"
    volumes:
      - '/lib/modules:/lib/modules/'
      - '/usr/src:/usr/src/'
      - '/sys/:/sys/'
      - '/home/tiagoduarte25/Desktop/thesis/quicsand-c/ag_low_lat_high_bw_1_1.xml:/topology.xml'
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    networks:
      - KollapsNet

  dashboard-f77c0191-ea42-4ed3-87a3-853354728fea:
    image: kollaps/dashboard:1.0
    ports:
      - "8088:8088"
    hostname: dashboard
    deploy:
      replicas: 1
    environment:
      KOLLAPS_UUID: 'f77c0191-ea42-4ed3-87a3-853354728fea'
      KOLLAPS_ORCHESTRATOR: swarm
    networks:
      - KollapsNet
      - outside

  client1-f77c0191-ea42-4ed3-87a3-853354728fea:
    image: quicsand
    entrypoint: ["/bin/sh", "-c", "mkfifo /tmp/Kollaps_hang; exec /bin/sh <> /tmp/Kollaps_hang #"]
    command: ['server','1']
    hostname: client1
    labels:
      f77c0191-ea42-4ed3-87a3-853354728fea: "true"
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
    environment:
      KOLLAPS_UUID: 'f77c0191-ea42-4ed3-87a3-853354728fea'
      KOLLAPS_ORCHESTRATOR: swarm
    networks:
      - KollapsNet

  server-f77c0191-ea42-4ed3-87a3-853354728fea:
    image: quicsand
    entrypoint: ["/bin/sh", "-c", "mkfifo /tmp/Kollaps_hang; exec /bin/sh <> /tmp/Kollaps_hang #"]
    hostname: server
    labels:
      f77c0191-ea42-4ed3-87a3-853354728fea: "true"
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
    environment:
      KOLLAPS_UUID: 'f77c0191-ea42-4ed3-87a3-853354728fea'
      KOLLAPS_ORCHESTRATOR: swarm
    networks:
      - KollapsNet

networks:
  KollapsNet:
    external:
      name: quicsand_network
  outside:
    driver: overlay

