version: "3.3"
services:
  bootstrapper:
    image: kollaps:2.0
    command: ["-s", "c1fce8aa-190e-461f-8e3f-f8a843b4b0f8"]
    deploy:
      mode: global
    environment:
      KOLLAPS_UUID: 'c1fce8aa-190e-461f-8e3f-f8a843b4b0f8'
      KOLLAPS_ORCHESTRATOR: swarm
      NUMBER_OF_GODS: 1
      POOL_PERIOD: 0.05
      MAX_FLOW_AGE: 2
    labels:
      bootc1fce8aa-190e-461f-8e3f-f8a843b4b0f8: "true"
    volumes:
      - '/lib/modules:/lib/modules/'
      - '/usr/src:/usr/src/'
      - '/sys/:/sys/'
      - '/home/tiagoduarte25/Desktop/thesis/quicsand-c/topology.xml:/topology.xml'
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    networks:
      - KollapsNet

  dashboard-c1fce8aa-190e-461f-8e3f-f8a843b4b0f8:
    image: kollaps/dashboard:1.0
    ports:
      - "8088:8088"
    hostname: dashboard
    deploy:
      replicas: 1
    environment:
      KOLLAPS_UUID: 'c1fce8aa-190e-461f-8e3f-f8a843b4b0f8'
      KOLLAPS_ORCHESTRATOR: swarm
    networks:
      - KollapsNet
      - outside

  client1-c1fce8aa-190e-461f-8e3f-f8a843b4b0f8:
    image: quicsand_client
    entrypoint: ["/bin/sh", "-c", "mkfifo /tmp/Kollaps_hang; exec /bin/sh <> /tmp/Kollaps_hang #"]
    command: ['server','1']
    hostname: client1
    labels:
      c1fce8aa-190e-461f-8e3f-f8a843b4b0f8: "true"
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
    environment:
      KOLLAPS_UUID: 'c1fce8aa-190e-461f-8e3f-f8a843b4b0f8'
      KOLLAPS_ORCHESTRATOR: swarm
    networks:
      - KollapsNet

  client2-c1fce8aa-190e-461f-8e3f-f8a843b4b0f8:
    image: quicsand_client
    entrypoint: ["/bin/sh", "-c", "mkfifo /tmp/Kollaps_hang; exec /bin/sh <> /tmp/Kollaps_hang #"]
    command: ['server','2']
    hostname: client2
    labels:
      c1fce8aa-190e-461f-8e3f-f8a843b4b0f8: "true"
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
    environment:
      KOLLAPS_UUID: 'c1fce8aa-190e-461f-8e3f-f8a843b4b0f8'
      KOLLAPS_ORCHESTRATOR: swarm
    networks:
      - KollapsNet

  client3-c1fce8aa-190e-461f-8e3f-f8a843b4b0f8:
    image: quicsand_client
    entrypoint: ["/bin/sh", "-c", "mkfifo /tmp/Kollaps_hang; exec /bin/sh <> /tmp/Kollaps_hang #"]
    command: ['server','3']
    hostname: client3
    labels:
      c1fce8aa-190e-461f-8e3f-f8a843b4b0f8: "true"
    deploy:
      replicas: 1
      endpoint_mode: dnsrr
    environment:
      KOLLAPS_UUID: 'c1fce8aa-190e-461f-8e3f-f8a843b4b0f8'
      KOLLAPS_ORCHESTRATOR: swarm
    networks:
      - KollapsNet

  server-c1fce8aa-190e-461f-8e3f-f8a843b4b0f8:
    image: quicsand_server
    entrypoint: ["/bin/sh", "-c", "mkfifo /tmp/Kollaps_hang; exec /bin/sh <> /tmp/Kollaps_hang #"]
    hostname: server
    labels:
      c1fce8aa-190e-461f-8e3f-f8a843b4b0f8: "true"
    deploy:
      replicas: 3
      endpoint_mode: dnsrr
    environment:
      KOLLAPS_UUID: 'c1fce8aa-190e-461f-8e3f-f8a843b4b0f8'
      KOLLAPS_ORCHESTRATOR: swarm
    networks:
      - KollapsNet

networks:
  KollapsNet:
    external:
      name: kollaps_network
  outside:
    driver: overlay

