#!/bin/bash
SCRIPT_NAME=$0

function usage {
    echo "usage: $SCRIPT_NAME <app_dir>"
    echo "  -app_dir                    name of the app to build: redis, iperf3,iperf3network,memcached and ping"
    echo "  -h/--help                   display this help message."
    exit 1
}

if [ "$#" -ne 1 ];
then
    echo "Illegal number of parameters!"
    usage
fi

if [[ ! -d "$1" ]];
then
    echo "Not supported app: $1."
    usage
fi

if [[ ! -d "Kollaps/examples/utils" ]];
then
    echo "Utils directory not found! Make sure you are running the script from the examples' home directory."
    exit 1
fi

case $1 in
    "quicsand")
        echo "Building images for the quicsand application..."
        docker build -f quicsand/src/client/Dockerfile -t quicsand_client .
        docker build -f quicsand/src/server/Dockerfile -t quicsand_server .
        ;;
    *)
        echo "Not supported app: $1."
        usage
        ;;
esac

echo "Building helper images..."
docker build -f Kollaps/examples/utils/dashboard/Dockerfile -t kollaps/dashboard:1.0 Kollaps/examples/utils/dashboard/
