#!/bin/bash

# Function to display usage
usage() {
    echo "Usage: $0 [-i <implementation>]" 1>&2
    echo "Options:" 1>&2
    echo "  -i, --implementation <implementation>   Specify the implementation (lsquic or msquic)" 1>&2
    exit 1
}

# Parse command-line arguments
while [[ "$#" -le 1 ]]; do
    usage
done

# Parse command-line arguments
while [[ "$#" -gt 0 ]]; do
    case $1 in
        -i|--implementation)
            IMPLEMENTATION="$2"
            shift
            ;;
        -h|--help)
            usage
            ;;
        *)
            echo "Error: Unknown option $1"
            usage
            ;;
    esac
    shift
done

# Check if the implementation is valid
if [ ! -d "implementations/$IMPLEMENTATION" ]; then
    echo "Error: Invalid implementation specified."
    usage
fi

cp quicsand/src/client_"$IMPLEMENTATION"/"$IMPLEMENTATION"_build.sh quicsand/src/client/build.sh
cp quicsand/src/server_"$IMPLEMENTATION"/"$IMPLEMENTATION"_build.sh quicsand/src/server/build.sh

# Remove all existing containers
docker rm -f $(docker ps -qa)

docker images | awk '$1 == "quicsand_client" {print $3}' | xargs -I {} docker rmi {}
docker images | awk '$1 == "quicsand_server" {print $3}' | xargs -I {} docker rmi {}
docker images | awk '$1 == "<none>" {print $3}' | xargs -I {} docker rmi {}

# Pass flags to docker-compose and start the containers
IMPLEMENTATION="$IMPLEMENTATION" docker compose build

# Check if the network is already created
if ! docker network ls | grep -q quicsand_network; then
    docker network create quicsand_network
else
    echo "Network 'quicsand_network' already created"
fi

# Check if the images exist
if docker images | grep -q quicsand_client && docker images | grep -q quicsand_server; then
    # Launch first process in a new terminal
    gnome-terminal -- bash -c "docker run -it --network=quicsand_network --name server quicsand_server; exec bash" &

    sleep 20

    # Launch second process in another new terminal
    gnome-terminal -- bash -c "docker run -it --network=quicsand_network --name client quicsand_client; exec bash"
else
    echo "Images quicsand_client and quicsand_server do not exist."
fi
