#!/bin/bash

rm -rf quicsand/bin/*

# Function to display usage
usage() {
    echo "Usage: $0 [-i <implementation>]" 1>&2
    echo "Options:" 1>&2
    echo "  -i, --implementation <implementation>   Specify the implementation (lsquic or msquic or quiche or ngtcp2)" 1>&2
    exit 1
}

# Parse command-line arguments
while [[ "$#" -le 1 ]]; do
    usage
done

# Parse command-line arguments
while [[ "$#" -gt 0 ]]; do
    case $1 in
        -i|--implementation)
            IMPLEMENTATION="$2"
            shift
            ;;
        -h|--help)
            usage
            ;;
        *)
            echo "Error: Unknown option $1"
            usage
            ;;
    esac
    shift
done

# rm -rf build
echo "Building $IMPLEMENTATION implementation"

if [ "$IMPLEMENTATION" == "msquic" ] || [ "$IMPLEMENTATION" == "lsquic" ] || [ "$IMPLEMENTATION" == "quiche" ] || [ "$IMPLEMENTATION" == "ngtcp2" ]; then
    cmake -S . -B build -DIMPL=$IMPLEMENTATION
else
    echo "Error: Unknown implementation $IMPLEMENTATION"
    usage
fi

cd build

make

cp -r ../quicsand/config.yaml bin/
cp -r ../quicsand/certs bin/

gnome-terminal -- bash -c "cd bin; ./server -c "/home/tiagoduarte25/Desktop/thesis/quicsand-c/quicsand/certs/quicsand-server.pem" -k "/home/tiagoduarte25/Desktop/thesis/quicsand-c/quicsand/certs/key.pem" -i "0.0.0.0" -p 4567; exec bash"

sleep 2

gnome-terminal -- bash -c "cd bin; ./client -i 127.0.0.1 -p 4567 -f /home/tiagoduarte25/Desktop/thesis/quicsand-c/resources/testing_files/file.txt; exec bash"

