#!/bin/bash

rm -rf quicsand/bin/*

# Function to display usage
usage() {
    echo "Usage: $0 [-i <implementation>]" 1>&2
    echo "Options:" 1>&2
    echo "  -i, --implementation <implementation>   Specify the implementation (lsquic or msquic)" 1>&2
    exit 1
}

# Parse command-line arguments
while [[ "$#" -le 1 ]]; do
    usage
done

# Parse command-line arguments
while [[ "$#" -gt 0 ]]; do
    case $1 in
        -i|--implementation)
            IMPLEMENTATION="$2"
            shift
            ;;
        -h|--help)
            usage
            ;;
        *)
            echo "Error: Unknown option $1"
            usage
            ;;
    esac
    shift
done

make IMPLEMENTATION="$IMPLEMENTATION" $IMPLEMENTATION

gnome-terminal -- bash -c "cd quicsand; LD_LIBRARY_PATH=/home/tiagoduarte25/Desktop/thesis/app/implementations/lsquic/src/liblsquic:/home/tiagoduarte25/Desktop/thesis/app/implementations/boringssl/ssl:/home/tiagoduarte25/Desktop/thesis/app/implementations/boringssl/crypto:$LD_LIBRARY_PATH ./bin/server/server; exec bash"

sleep 2

gnome-terminal -- bash -c "cd quicsand; LD_LIBRARY_PATH=/home/tiagoduarte25/Desktop/thesis/app/implementations/lsquic/src/liblsquic:/home/tiagoduarte25/Desktop/thesis/app/implementations/boringssl/ssl:/home/tiagoduarte25/Desktop/thesis/app/implementations/boringssl/crypto:$LD_LIBRARY_PATH ./bin/client/client; exec bash"