FROM python:3.9-slim

# Set the working directory
WORKDIR /app

RUN pip install --no-cache-dir pyyaml

# Copy the TopologyGenerator script and any other necessary files
COPY TopologyGenerator.py .

# Set the entrypoint to run the TopologyGenerator script
ENTRYPOINT ["python", "TopologyGenerator.py"]